###checking product api
post http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
    "name":"marich",
    "email":"5456@a.com",
    "phone":"sfsdf",
    "password":"justwow"
}

