###checking register api
post http://localhost:8001/api/v1/user/register
Content-Type: application/json

{
    "fName":"marich",
    "lName":"marich",
    "email":"a@a.com",
    "password":"justwow"
}

###checking login api
post http://localhost:8001/api/v1/user/login
Content-Type: application/json

{
    "email":"a@a.com",
    "password":"justwow"
}